# # Welcome to Jekyll!
# #
# # This config file is meant for settings that affect your whole blog, values
# # which you are expected to set up once and rarely edit after that. If you find
# # yourself editing this file very often, consider using Jekyll's data files
# # feature for the data you need to update frequently.
# #
# # For technical reasons, this file is *NOT* reloaded automatically when you use
# # 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# # Site settings
# # These are used to personalize your new site. If you look in the HTML files,
# # you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# # You can create any custom variable you would like, and they will be accessible
# # in the templates via {{ site.myvariable }}.
# title: mattsu
# email: deqi.su@gmail.com
# description: > # this means to ignore newlines until "baseurl:"
#   东坡奇客, blog of an eastlakeside hacker, all about zen and python.
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: mattsu
# github_username:  suqi

# # Build settings
# markdown: kramdown
# theme: minima
# #theme: jekyll-theme-cayman
# gems:
#   - jekyll-feed
# exclude:
#   - Gemfile
#   - Gemfile.lock

# ---- above is default ---------------


# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://eastlakeside.cn
date_format: "ordinal"
title: 一只特立独行的苏
subtitle: "代码之外，实现身心自由"
description: ""
keywords: matt su, 大牙马特, 马特苏, 老苏, dphacker, suqi, qisuker
favicon: /favicon.ico
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 3

# ---------------- #
#      Author      #
# ---------------- #
author: 老苏
organization: EastLakeSide
organization_url: https://github.com/eastlakeside
location: Zhuhai, China
email: matt.su@foxmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 主页
  -
    href: https://py.eastlakeside.cn
    label: 译作《Python进阶》
    target: _blank
  -
    href: /about/
    label: 关于

  # -
  #   href: /categories/
  #   label: 分类


# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    # - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    # - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
# collections:
#     wiki:
#         output: true
#         permalink: /wiki/:path/

repository: suqi/

# ---------------- #
#      Socials     #
# ---------------- #
github_username: suqi
# douban_username: freedim
# facebook_username: mzlogin
# weibo_username: mzlogin
# zhihu_username: mzlogin
twitter_username: dphacker

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, duoshuo
# comments_provider: disqus
# # !!!重要!!! 请修改下面两个用户名为你自己申请的
# # !!!Important!!! Please modify usernames below to yours
# duoshuo_username: mazhuang
# disqus_username: mzlogin
# # 在使用 disqus 的时候可点击显示多说评论框
# lazy_load_duoshuo: true

# ---------------- #
#    Analytics     #
# ---------------- #
# google:
#     analytics_id: UA-80669434-1

# ---------------- #
#      Datas       #
# ---------------- #
skill_software_keywords: [Productivity, Python, Django, Celery, Vue.js, Bootstrap]



